### ISSUE TITLE
Remark: Needs entry "Standard" Shipping

### ISSUE THREAD

**Issue by amenk** [shopware/acceptance-test-suite#125]
The suite expects a shipping method "Standard", otherwise a Storefront test will bail out here:

```
const getDefaultShippingMethodId = async (adminApiContext) => {
  const resp = await adminApiContext.post("search/shipping-method", {
    data: {
      limit: 1,
      filter: [{
        type: "equals",
        field: "name",
        value: "Standard"
      }]
    }
  });
  const result = await resp.json();
  return result.data[0].id; <--- not defined
};
```

Maybe it can be documented or made more robust, because of this claim in the README:

> The test suite is designed to test against any Shopware instance with pure API usage.

**Comment by frobel** [comment]
Hey, thx for your contribution and hint for that method. We adjusted the documentation and added already a method which is more flexible and maybe fits your needs. Checkout [here](https://github.com/shopware/acceptance-test-suite/blob/92df111d41e7cf4530fe12cb142edf329ed916f3/src/services/TestDataService.ts#L969)

**Comment by amenk** [comment]
@frobel thanks, see also here: https://github.com/shopware/acceptance-test-suite/issues/305
